# Lab 7 - Summarizing a Health Survey

## Background

The file health_survey.csv contains the responses to a series of health-related questions.  Dr. Bergen, Director of the Statistical Consulting Center at WSU, needs you to prepare the attached data for analysis.  Please perform the following steps to prepare the required csv file.

Dr. Bergen had a follow-up meeting with his client and it was determined that we need to redo the file construction from an earlier assignment.  Recall that the file `health_survey.csv` contains the responses to a series of health-related questions. We need to code the responses as 1-5 using the definition below.   Some of the columns need a reverse coding (see the *Needs Reverse Coding?* column in `ReverseCodingItems.csv`.

The following table describes the coding that should be used for both types of questions.

|Old Label                     |New Coded Value  |Reverse Coding
|------------------------------|-----------------|----------------
|"Strongly Disagree"           |1                |5
|"Somewhat Disagree"           |2                |4
|"Neither Agree nor Disagree"  |3                |3
|"Somewhat Agree"              |4                |2
|"Strongly Agree"              |5                |1

## Tasks

%reset

In [24]:
import pandas as pd
from dfply import *

In [38]:

survey_data = pd.read_csv('./data/health_survey.csv',)
survey_data.head()

,Unnamed: 0,F1,F5,F2,F1.1,F2.1,F6,F4,F3,F5.1,...,F2.9,F3.4,F4.3,F2.10,F1.7,F6.4,F4.4,F5.7,F3.5,F2.11
0,1,Somewhat Agree,Somewhat Disagree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Somewhat Disagree,Somewhat Agree,Somewhat Agree,Somewhat Agree,...,Somewhat Agree,Somewhat Disagree,Neither Agree nor Disagree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Somewhat Agree
1,2,Somewhat Agree,Somewhat Disagree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Somewhat Disagree,Somewhat Agree,Neither Agree nor Disagree,Neither Agree nor Disagree,...,Somewhat Agree,Somewhat Agree,Neither Agree nor Disagree,Somewhat Agree,Somewhat Agree,Somewhat Disagree,Neither Agree nor Disagree,Somewhat Agree,Neither Agree nor Disagree,Somewhat Agree
2,3,Strongly Agree,Neither Agree nor Disagree,Somewhat Agree,Strongly Agree,Strongly Agree,Somewhat Disagree,Somewhat Agree,Somewhat Agree,Somewhat Agree,...,Somewhat Agree,Somewhat Agree,Neither Agree nor Disagree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Strongly Agree,Strongly Disagree,Somewhat Agree
3,4,Somewhat Agree,Somewhat Agree,Strongly Agree,Somewhat Agree,Strongly Agree,Neither Agree nor Disagree,Neither Agree nor Disagree,Somewhat Disagree,Somewhat Agree,...,Somewhat Agree,Somewhat Disagree,Somewhat Agree,Somewhat Agree,Neither Agree nor Disagree,Neither Agree nor Disagree,Neither Agree nor Disagree,Somewhat Agree,Somewhat Disagree,Somewhat Agree
4,5,Strongly Agree,Strongly Disagree,Neither Agree nor Disagree,Strongly Agree,Somewhat Agree,Strongly Disagree,Strongly Agree,Somewhat Agree,Neither Agree nor Disagree,...,Somewhat Agree,Somewhat Agree,Neither Agree nor Disagree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Somewhat Agree,Strongly Agree,Somewhat Disagree,Somewhat Agree

In [41]:
survey_data["Participant"] = survey_data['Unnamed: 0']

In [42]:
survey_data = survey_data >> drop(X['Unnamed: 0'])

In [43]:
survey_data.columns

Index(['F1', 'F5', 'F2', 'F1.1', 'F2.1', 'F6', 'F4', 'F3', 'F5.1', 'F1.2',
       'F2.2', 'F6.1', 'F2.3', 'F4.1', 'F2.4', 'F5.2', 'F2.5', 'F6.2', 'F1.3',
       'F2.6', 'F5.3', 'F4.2', 'F2.7', 'F3.1', 'F2.8', 'F5.4', 'F3.2', 'F1.4',
       'F3.3', 'F1.5', 'F5.5', 'F6.3', 'F1.6', 'F5.6', 'F2.9', 'F3.4', 'F4.3',
       'F2.10', 'F1.7', 'F6.4', 'F4.4', 'F5.7', 'F3.5', 'F2.11',
       'Participant'],
      dtype='object')

In [44]:
reverse = pd.read_csv('./ReverseCodingItems.csv', names=['Q', 'Construct', 'Qualtrics', 'Needs_Reverse_Coding', 'Question'], header = 0)
reverse.head()

,Q,Construct,Qualtrics,Needs_Reverse_Coding,Question
0,"In the future, I plan to participate in a comm...",1,1,No,F1
1,Individuals are responsible for their own misf...,5,2,Yes,F5
2,When tryng to understand the position of other...,2,3,No,F2
3,I plan to become involved in my community,1,4,No,F1.1
4,I can communicate well with others,2,5,No,F2.1

#### Task 1  

Look at the questions that need reverse coding and explain why it makes sense to reverse the coding on these items.

In [45]:
#> *Your thoughts here*
reverse >> select([X.Q,X.Needs_Reverse_Coding])>>filter_by(X.Needs_Reverse_Coding=='Yes')

                                                    Q Needs_Reverse_Coding
1   Individuals are responsible for their own misf...                  Yes
5   It is hard for a group to function effectively...                  Yes
13               I am a better follower than a leader                  Yes
15  We need to look no further than the individual...                  Yes
30     People are poor because they choose to be poor                  Yes
31  I find it difficult to relate to people from a...                  Yes
33  I don't understand why some people are poor wh...                  Yes
36  I would rather have sombody else take the lead...                  Yes
39  I prefer the company of people who are very si...                  Yes

Because the meaning of the question is negative instead of other way around...

#### Task 2 

You will need to redo the file construction, but now need to take the reverse coding into account. **For each step, paste a screenshot of the JMP dialog or formula associated with the outcome.**

1.  *Stack* the columns.

![](img/survey/image1.png)

In [46]:
cols = ['F1', 'F5', 'F2', 'F1.1', 'F2.1', 'F6', 'F4', 'F3',
       'F5.1', 'F1.2', 'F2.2', 'F6.1', 'F2.3', 'F4.1', 'F2.4', 'F5.2', 'F2.5',
       'F6.2', 'F1.3', 'F2.6', 'F5.3', 'F4.2', 'F2.7', 'F3.1', 'F2.8', 'F5.4',
       'F3.2', 'F1.4', 'F3.3', 'F1.5', 'F5.5', 'F6.3', 'F1.6', 'F5.6', 'F2.9',
       'F3.4', 'F4.3', 'F2.10', 'F1.7', 'F6.4', 'F4.4', 'F5.7', 'F3.5',
       'F2.11']
survey_stacked = (survey_data 
                 >> gather("Question","Response", cols))
survey_stacked >> head

   Participant Question        Response
0            1       F1  Somewhat Agree
1            2       F1  Somewhat Agree
2            3       F1  Strongly Agree
3            4       F1  Somewhat Agree
4            5       F1  Strongly Agree

2.  Read in and join `ReverseCodingItems.csv` to add a new column called `NeedsReverse` to the health survey dataframe. 

![](img/survey/image2.png)

In [47]:
survey_join = survey_stacked >> right_join(reverse, by='Question') >> drop('Q', 'Construct', 'Qualtrics')
survey_join.head()

   Participant Question        Response Needs_Reverse_Coding
0            1       F1  Somewhat Agree                   No
1            2       F1  Somewhat Agree                   No
2            3       F1  Strongly Agree                   No
3            4       F1  Somewhat Agree                   No
4            5       F1  Strongly Agree                   No

3.  Make a new column called `TempCodedValue` by recoding the `Question`s column.

![](img/survey/image3.png)

In [48]:
scale = {'Somewhat Agree': 4 , "Strongly Agree": 5 , "Neither Agree nor Disagree": 3, "Somewhat Disagree": 2, "Strongly Disagree": 1}
survey_temp_recode = survey_join >> mutate(TempRecodeValue = X.Response.map(scale))
survey_temp_recode.head()

   Participant Question        Response Needs_Reverse_Coding  TempRecodeValue
0            1       F1  Somewhat Agree                   No              4.0
1            2       F1  Somewhat Agree                   No              4.0
2            3       F1  Strongly Agree                   No              5.0
3            4       F1  Somewhat Agree                   No              4.0
4            5       F1  Strongly Agree                   No              5.0

4.  Make a new column called `TempReverseValue` by recoding the `Question`s column.

![](img/survey/image4.png)

In [49]:
reverse_scale = {1.0: 5, 2.0: 4, 3.0:3, 4.0:2, 5.0: 1 }
survey_temp_reverse = survey_temp_recode >> mutate(TempReverseValue = X.TempRecodeValue.map(reverse_scale))
survey_temp_reverse.head()

,Participant,Question,Response,Needs_Reverse_Coding,TempRecodeValue,TempReverseValue
0,1,F1,Somewhat Agree,No,4.0,2.0
1,2,F1,Somewhat Agree,No,4.0,2.0
2,3,F1,Strongly Agree,No,5.0,1.0
3,4,F1,Somewhat Agree,No,4.0,2.0
4,5,F1,Strongly Agree,No,5.0,1.0

5.  Make a new column called `RecodedValue` that holds the correct
    value for each question based on the value in `NeedsReverse`.

![](img/survey/image5.png)

In [50]:
from more_dfply import ifelse

In [51]:
survey_new = survey_temp_reverse >> mutate(RecodedValue = ifelse(X.Needs_Reverse_Coding == 'Yes', X.TempReverseValue, X.TempRecodeValue ))
survey_new.head()

,Participant,Question,Response,Needs_Reverse_Coding,TempRecodeValue,TempReverseValue,RecodedValue
0,1,F1,Somewhat Agree,No,4.0,2.0,4.0
1,2,F1,Somewhat Agree,No,4.0,2.0,4.0
2,3,F1,Strongly Agree,No,5.0,1.0,5.0
3,4,F1,Somewhat Agree,No,4.0,2.0,4.0
4,5,F1,Strongly Agree,No,5.0,1.0,5.0

6.  Make a new column by *Recoding* the Question Types to *F1, F2, ..., F6. *

![](img/survey/image6.png)

In [52]:
def get(x):
    return x.split('.')[0]

In [53]:
survey_question_type = survey_new >> mutate(QuestionType = X.Question.map(get))
survey_question_type.head()

,Participant,Question,Response,Needs_Reverse_Coding,TempRecodeValue,TempReverseValue,RecodedValue,QuestionType
0,1,F1,Somewhat Agree,No,4.0,2.0,4.0,F1
1,2,F1,Somewhat Agree,No,4.0,2.0,4.0,F1
2,3,F1,Strongly Agree,No,5.0,1.0,5.0,F1
3,4,F1,Somewhat Agree,No,4.0,2.0,4.0,F1
4,5,F1,Strongly Agree,No,5.0,1.0,5.0,F1

7.  *Aggregate* and *Unstack*.

![](img/survey/image7.png)
![](img/survey/image8.png)

In [54]:
survey_agg = survey_question_type >> group_by(X.Participant, X.QuestionType) >> summarise(RecodedTotal = X.RecodedValue.sum())
survey_agg.head()

  QuestionType  Participant  RecodedTotal
0           F1            1          31.0
1           F2            1          48.0
2           F3            1          20.0
3           F4            1          17.0
4           F5            1          28.0

In [55]:
survey_unstack = survey_agg >> spread(X.QuestionType, X.RecodedTotal) 
survey_unstack.head()

   Participant    F1    F2    F3    F4    F5    F6
0            1  31.0  48.0  20.0  17.0  28.0  18.0
1            2  31.0  47.0  19.0  17.0  27.0  20.0
2            3  36.0  46.0  19.0  18.0  32.0  17.0
3            4  32.0  54.0  12.0  15.0  30.0  16.0
4            5  37.0  47.0  22.0  19.0  36.0  19.0

#### Task 3

Repackage all of your code in one pipe then write the final output to `health_survey_summary.csv`

In [65]:
survey_all = (survey_data >> gather("Question","Response", cols) \
           >> right_join(reverse, by='Question') >> drop('Q', 'Construct', 'Qualtrics') \
           >> mutate(TempRecodeValue = X.Response.map(scale)) \
           >> mutate(TempReverseValue = X.TempRecodeValue.map(reverse_scale)) \
           >> mutate(RecodedValue = ifelse(X.Needs_Reverse_Coding == 'Yes', X.TempReverseValue, X.TempRecodeValue )) \
           >> mutate(QuestionType = X.Question.map(get))
           >> group_by(X.Participant, X.QuestionType) >> summarise(RecodedTotal = X.RecodedValue.sum())         
           >> spread(X.QuestionType, X.RecodedTotal))          
survey_all.head()

   Participant    F1    F2    F3    F4    F5    F6
0            1  31.0  48.0  20.0  17.0  28.0  18.0
1            2  31.0  47.0  19.0  17.0  27.0  20.0
2            3  36.0  46.0  19.0  18.0  32.0  17.0
3            4  32.0  54.0  12.0  15.0  30.0  16.0
4            5  37.0  47.0  22.0  19.0  36.0  19.0

In [66]:
survey_all.to_csv('./data/health_survey_summary.csv')